In [15]:
from astropy.io import fits
from astropy.wcs import WCS
import astropy.units as u
import numpy as np
import sunpy.coordinates
from sunpy.coordinates import Helioprojective
from astropy.coordinates import SkyCoord

In [16]:
with fits.open('../../src/SPICE/20221024/solo_L2_spice-n-ras_20221024T231535_V07_150995398-000.fits') as hdul:
    wcs_spice = WCS(hdul[0].header).dropaxis(2)
    x, y, t = np.meshgrid(np.arange(0,2),
                        np.arange(0, 2),
                        np.arange(0, 2))
    print(wcs_spice.pixel_to_world(x,y,t))

[<SkyCoord (Helioprojective: obstime=2022-10-25T00:51:59.753, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2022-10-25T00:51:59.753, rsun=695700.0 km): (lon, lat, radius) in (deg, deg, m)
    (-50.59290147, 6.48623548, 5.92481369e+10)>): (Tx, Ty) in arcsec
    [[[(718.41148829, -46.3682358 ), (718.41148829, -46.3682358 )],
      [(722.39804299, -46.04082854), (722.39804299, -46.04082854)]],

     [[(718.32161058, -45.27392775), (718.32161058, -45.27392775)],
      [(722.30816532, -44.94652046), (722.30816532, -44.94652046)]]]>, <Time object: scale='utc' format='mjd' value=[[[59877.10270249 59877.10271406]
  [59877.10200515 59877.10201672]]

 [[59877.10270249 59877.10271406]
  [59877.10200515 59877.10201672]]]>]


keyword looks very much like CROTAn but isn't. [astropy.wcs.wcs]
Set MJD-OBS to 59876.969164 from DATE-OBS.
Set MJD-BEG to 59876.969164 from DATE-BEG.
Set MJD-AVG to 59877.036108 from DATE-AVG.
Set MJD-END to 59877.103050 from DATE-END'. [astropy.wcs.wcs]


In [7]:
with fits.open('../../src/SPICE/20221024/solo_L2_spice-n-ras_20221024T231535_V07_150995398-000.fits') as hdul:
    wcs_spice = WCS(hdul[0].header).dropaxis(2)
    x, y, t = np.meshgrid(np.arange(0,2),
                        np.arange(0, 2),
                        np.arange(0, 2))
    print(wcs_spice.pixel_to_world(x,y,t))

[<SkyCoord (Helioprojective: obstime=2022-10-25T00:51:59.753, rsun=695700.0 km, observer=<HeliographicStonyhurst Coordinate (obstime=2022-10-25T00:51:59.753, rsun=695700.0 km): (lon, lat, radius) in (deg, deg, m)
    (-50.59290147, 6.48623548, 5.92481369e+10)>): (Tx, Ty) in arcsec
    [[[(718.41148829, -46.3682358 ), (718.41148829, -46.3682358 )],
      [(722.39804299, -46.04082854), (722.39804299, -46.04082854)]],

     [[(718.32161058, -45.27392775), (718.32161058, -45.27392775)],
      [(722.30816532, -44.94652046), (722.30816532, -44.94652046)]]]>, <Time object: scale='utc' format='mjd' value=[[[59877.10270249 59877.10271406]
  [59877.10200515 59877.10201672]]

 [[59877.10270249 59877.10271406]
  [59877.10200515 59877.10201672]]]>]


keyword looks very much like CROTAn but isn't. [astropy.wcs.wcs]
Set MJD-OBS to 59876.969164 from DATE-OBS.
Set MJD-BEG to 59876.969164 from DATE-BEG.
Set MJD-AVG to 59877.036108 from DATE-AVG.
Set MJD-END to 59877.103050 from DATE-END'. [astropy.wcs.wcs]


In [17]:
with fits.open('../../src/SPICE/20221024/solo_L2_spice-n-ras_20221024T231535_V07_150995398-000.fits') as hdul:
    wcs_spice = WCS(hdul[0].header).dropaxis(2)
    x, y, t = np.meshgrid(np.arange(0,2),
                        np.arange(0, 2),
                        np.arange(0, 2))
    print(wcs_spice.pixel_to_world_values(x,y,t))

(array([[[0.19955875, 0.19955875],
        [0.20066612, 0.20066612]],

       [[0.19953378, 0.19953378],
        [0.20064116, 0.20064116]]]), array([[[-0.01288007, -0.01288007],
        [-0.01278912, -0.01278912]],

       [[-0.01257609, -0.01257609],
        [-0.01248514, -0.01248514]]]), array([[[11537.75, 11538.75],
        [11477.5 , 11478.5 ]],

       [[11537.75, 11538.75],
        [11477.5 , 11478.5 ]]]))


keyword looks very much like CROTAn but isn't. [astropy.wcs.wcs]
Set MJD-OBS to 59876.969164 from DATE-OBS.
Set MJD-BEG to 59876.969164 from DATE-BEG.
Set MJD-AVG to 59877.036108 from DATE-AVG.
Set MJD-END to 59877.103050 from DATE-END'. [astropy.wcs.wcs]
